[package]
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Adaptive Replacement Cache (ARC) with automatic eviction based on access frequency and recency"
keywords = ["cache", "caching", "arc", "eviction", "replacement"]
license = "MIT/Apache-2.0"
name = "arc-cache"
repository = "https://github.com/jedisct1/rust-arc-cache"
version = "0.2.7"
categories = ["algorithms", "caching", "memory-management"]
edition = "2018"

[dependencies]
xlru-cache = "0.1"

[dev-dependencies]
nohash-hasher = "0.2"

[badges]
appveyor  = { repository = "jedisct1/rust-arc-cache" }
